### ISSUE TITLE
`tb push` needs to print out verbose logs

### ISSUE THREAD

**Issue by fwang** [AnomalyInnovations/toolbeam-cli#6]
tb push
validating json...
analyzing tools...
etc

**Comment by jayair** [comment]
Printing added/removed tools in `tb push` (81f191a4f6057d2935c8eeac96351323a03afc85, 9f8ce655b2672501e7880578b72ef29f5dc1c4fd & f5a9c6ddde01e72efbe94a0a473763eee357c85e).
